// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVhIObPYVKjt-i-kg5xCCI6QT0YPyf37s',
    appId: '1:760743155657:web:6fbd0c3d5f4aa41cedba18',
    messagingSenderId: '760743155657',
    projectId: 'bookapp-6501f',
    authDomain: 'bookapp-6501f.firebaseapp.com',
    storageBucket: 'bookapp-6501f.appspot.com',
    measurementId: 'G-4CSVR1LGDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeLrWa82qS-bFSgTtFf7csL_dKb8urBeo',
    appId: '1:760743155657:android:5bb8c34243af7230edba18',
    messagingSenderId: '760743155657',
    projectId: 'bookapp-6501f',
    storageBucket: 'bookapp-6501f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3KcSK69xl5X0ySI_mIHTQ637Wz7GUFQw',
    appId: '1:760743155657:ios:aeff4ea9e3a44829edba18',
    messagingSenderId: '760743155657',
    projectId: 'bookapp-6501f',
    storageBucket: 'bookapp-6501f.appspot.com',
    iosClientId: '760743155657-qe5ck2totn6qsjg0ui4nf7vhd43mhnvt.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3KcSK69xl5X0ySI_mIHTQ637Wz7GUFQw',
    appId: '1:760743155657:ios:aeff4ea9e3a44829edba18',
    messagingSenderId: '760743155657',
    projectId: 'bookapp-6501f',
    storageBucket: 'bookapp-6501f.appspot.com',
    iosClientId: '760743155657-qe5ck2totn6qsjg0ui4nf7vhd43mhnvt.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookApp',
  );
}
